### ISSUE TITLE
Order dependant behaviour when used with BibLaTex

### ISSUE THREAD

**Issue by ElieGouzien** [compholio/jabbrv#11]
General description
================
I've noticed that the behavior of `jabbrv` with `biblatex` depend on the order of the `\usepackage{}` commands.

Note that in the ![example tex file](https://github.com/compholio/jabbrv/blob/master/biblatex-example.tex), `usepackage{jabbrv}` is used twice.

Examples
========
The examples I show here are inspired by ![biblatex-example.tex](https://github.com/compholio/jabbrv/blob/master/biblatex-example.tex), and use the same ![bibtex file](https://github.com/compholio/jabbrv/blob/master/example.bib).

Working case
-----------------
```latex
\documentclass[letterpaper,12pt]{article}

\usepackage{jabbrv}

\usepackage[backend=biber, style=numeric-comp]{biblatex}
\addbibresource{example.bib}

\DefineJournalAbbreviation{Test}{Tes} % <-- Note that there is no period!

\begin{document}
Test \cite{ref:TestNoPeriod,ref:Test,ref:TestPeriod,ref:TestPeriodTwoWords,ref:TestPeriodRefInf,ref:TestPeriodInf,
ref:TestMyAbbrvOneWord,ref:TestMyAbbrvTwoWords,ref:TestPeriodInfPeriod,ref:AbbrvTest,ref:SymbolTest}.
\JournalTitle{Briefings in Functional Genomics}.

\printbibliography
\end{document}
```
It gives the following output :
[biblatex-example.pdf](https://github.com/compholio/jabbrv/files/3430837/biblatex-example.pdf)

Not working case
----------------------
```latex
\documentclass[letterpaper,12pt]{article}

\usepackage[backend=biber, style=numeric-comp]{biblatex}
\addbibresource{example.bib}

\usepackage{jabbrv}
\DefineJournalAbbreviation{Test}{Tes} % <-- Note that there is no period!

\begin{document}
Test \cite{ref:TestNoPeriod,ref:Test,ref:TestPeriod,ref:TestPeriodTwoWords,ref:TestPeriodRefInf,ref:TestPeriodInf,
ref:TestMyAbbrvOneWord,ref:TestMyAbbrvTwoWords,ref:TestPeriodInfPeriod,ref:AbbrvTest,ref:SymbolTest}.
\JournalTitle{Briefings in Functional Genomics}.

\printbibliography
\end{document}
 ```

It gives the following output :
[biblatex-example.pdf](https://github.com/compholio/jabbrv/files/3430846/biblatex-example.pdf)

Remarks
=======
Also note that that in ![the example](https://github.com/compholio/jabbrv/blob/master/biblatex-example.pdf), `\tjri` is not replaced by its value.
I've not put it into my examples.

**Comment by compholio** [comment]
Wow, I totally missed that I had that in twice - I'll take a look and see what I can figure out.

**Comment by compholio** [comment]
Please check and see if commit f00da3a (works for me).  biblatex uses AtBeginDocument to defer its behavior, so the way I had it before that meant that the deferred behavior I requested came after biblatex's deferral.  Fortunately, AtEndPreamble fixes this by waiting until after the entire preamble is processed but before the \begin{document} processing occurs.

**Comment by ElieGouzien** [comment]
This breaks the latex-example.tex file and also when `jabbrv` is imported before biblatex, since `\AtEndPreamble` is not a LaTeX command.

The only way I've found to fix it is to add `\RequirePackage{etoolbox}` in `jabbrv.sty`.
With it it's all working as expected.

**Comment by compholio** [comment]
Heh, that explains why another project I made a long time ago didn't use that...  Try commit cb107a0b437aa8dc1a3999ae6c271f861af60df0 ;)

**Comment by ElieGouzien** [comment]
This time it's working perfectly. I'm quite impressed by your LaTeX skills!

So thanks a lot for having made jabbrv fully compatible with biblatex; this will be clearly very useful!

**Comment by compholio** [comment]
No problem, glad I can help!  I've also been putting together an update to pull in a more recent LTWA and fix Bug #3, if I put that up in a branch would you be interested in testing it?

**Comment by ElieGouzien** [comment]
Yes, for sure.

**Comment by compholio** [comment]
Awesome, give this branch a try and see if you have any trouble:
https://github.com/compholio/jabbrv/tree/UpdateLTWA

**Comment by ElieGouzien** [comment]
I took time to test the UpdateLTWA branch.
I did not find any introduced bug.

However, there is some strange changes in `jabbrv-ltwa-all.ldf`; for instance:
```diff
-\DefineJournalPartialAbbreviation{Biolog}{Biol}
+\DefineJournalPartialAbbreviation{B\`iolog}{Biol}
```
but it might not be a problem but just that the abbreviation was moved somewhere else; and the new example `ref:TestDiacritic` works. I really think this is not a problem. 

I Also noticed some possible issues.


Downloading new `.ldf`
----------------------

I got the following warning while running `download-abbrv.sh` (with debian, maybe not clean install):
> ./extract-abbrv-lang.sh: line 76: <(echo "${ENTRY}"): Too many open files
> ./extract-abbrv-lang.sh: cannot make pipe for command substitution: Too many open files

and it resulted in ldf files with fewer definitions than on the list you extracted.
This might not be a true problem, since you provide the `.ldf` files.

Internationalization issues
---------------------------
I also discovered some issues when tried with random journal names in French (but can certainly also a problem in other languages):
  * When a word starts without a capital letter, it is not abbreviated ; at least ![in French](https://fr.wikipedia.org/wiki/Wikip%C3%A9dia:Conventions_typographiques#Principes_de_capitalisation_des_titres) we usually put only the first word in capital letter (sometime also an article before the first word).
  * Using apostrophe between words makes jabbrv failing; you could think of "Journal d'agriculture" that fails even if I write it "Journal d'Agriculture" (what should not be done).
  * With BibLaTeX or using the `\JournalTitle{}` command, using directly Unicode characters (diacritic marks) fail.

However, both does not constitute regressions, and I think it should not prevent you from realeasing your last work.

Random remarks
--------------

+ You prettified `latex-example.tex` but not `biblatex-example.tex`. Idem for the new examples.
+ You should maybe talk about the compatibility with BibLaTeX in `Readme.md`.

As a conclusion I think the branch is ready for release, and if you want I can open new issues for the different remarks I had.

**Comment by compholio** [comment]
Thanks @ElieGouzien, this is all very helpful.  The Biolog/B\`iolog thing is a change in the LTWA itself that took me a while to figure out (that's why the new `ref:TestDiacritic` example exists).  I would definitely appreciate it if you opened issues for the other things that you encountered, but I'm happy to hear that it doesn't look like there are any regressions :)
