### ISSUE TITLE
\DefineSpuriousJournalWord{} are English only

### ISSUE THREAD

**Issue by ElieGouzien** [compholio/jabbrv#15]
The `\DefineSpuriousJournalWord{}` should certainly not be hard-coded into jabbrv.sty but moved into the `.ldf` files and be language dependent.

Reading the ISO-4 text should help to now how it should be done.

**Comment by compholio** [comment]
Because these files are auto-generated from the ISSN database, I think it would be best to keep the default spurious words in the main style file but handle them in a language-specific way.  How does something like this sound?:
```
\def\jabbrv@lang@spurious@en{
    \DefineSpuriousJournalWord{of}
    \DefineSpuriousJournalWord{in}
    \DefineSpuriousJournalWord{and}
    \DefineSpuriousJournalWord{the}
}
\csname jabbrv@lang@spurious@\jabbrv@lang\endcsname
```
