### ISSUE TITLE
Apostrophe sometime prevent detection of abbreviation

### ISSUE THREAD

**Issue by ElieGouzien** [compholio/jabbrv#16]
Using apostrophe between words (typically between an article and a noun) makes jabbrv failing; you could think of "Journal d'agriculture" that fails even if I write it "Journal d'Agriculture" (what should not be done).

It's not obvious how it should be dealt with since LTWA define words containing apostrophe, and usually the cases where it should be considered as separing words is between a "spurious word" and another. See also #15.

**Comment by compholio** [comment]
The capitalization is obviously a separate issue (Issue #14), but I've been thinking about ways to approach this and it _might_ be doable.  I'm not particularly familiar with French, is the correct behavior in this situation to drop the `d'` and abbreviate the rest?

**Comment by ElieGouzien** [comment]
Yes, I think it is the correct behaviour (but I didn't check on the exact rules).
The `d'` is a contraction of `de` (to avoid repeated vowel), and play the same role as `of` in English.

**Comment by compholio** [comment]
When you get a chance, please give this new version a try.  At the moment only `d'` is defined, but you can add additional prefixes to remove like so:
```
\DefineSpuriousJournalPrefix{d'}
```
