### ISSUE TITLE
Documenting compatibility with BibLaTeX

### ISSUE THREAD

**Issue by ElieGouzien** [compholio/jabbrv#18]
Compatibility with BibLaTeX should be mentioned in Readme.md.
Also it might be a good idea to prettify biblatex-example.tex, and insert the new examples.

**Comment by LavendaRaphael** [comment]
Yes, if not your mention, I have ignored the example.

**Comment by compholio** [comment]
I've added a note to the README in d922ed6c3880538817d3ad3c39bc745f88702941.  I would be happy to take a pull request on improving the example.
