### ISSUE TITLE
Support URL typesetting for jabrv_ieeetr style

### ISSUE THREAD

**Issue by krishnakumarg1984** [compholio/jabbrv#19]
Thanks a lot for this wonderful package.  I found it immensely useful for my work. There is a minor issue though.

The `IEEEtran.bst` style format supplied as part of the CTAN IEEEtran package bundle correctly typesets URLs in the `bib` file with the actual URL followed by the words "[Online]. Available:"  and terminated without a period at the end. See detailed explanation in the package's [bib/bst manual](http://mirrors.ctan.org/macros/latex/contrib/IEEEtran/bibtex/IEEEtran_bst_HOWTO.pdf).

See this typeset output to see the difference. The left image is from IEEEtran original, and the right image is with the `jabbrv_ieeetr` style.

<img width="901" alt="missing_url_field" src="https://user-images.githubusercontent.com/15239509/65193815-43cbc500-da74-11e9-93ff-95e4f7873782.PNG">

Here is the corresponding source bib entry for the citation with the URL field
```

@article{Ahmed2014,
author = {Ahmed, Ryan and {El Sayed}, Mohammed and Arasaratnam, Ienkaran and {Jimi Tjong} and Habibi, Saeid},
doi = {10.1109/JESTPE.2014.2331059},
file = {::},
issn = {2168-6777},
journal = {IEEE Journal of Emerging and Selected Topics in Power Electronics},
month = {sep},
number = {3},
pages = {659--677},
title = {{Reduced-Order Electrochemical Model Parameters Identification and SOC Estimation for Healthy and Aged Li-Ion Batteries Part I: Parameterization Model Development for Healthy Batteries}},
url = {http://ieeexplore.ieee.org/document/6838950/},
volume = {2},
year = {2014}
}
```

Can you please help to have the IEEE style of URL typesetting with `jabbrv`?

**Comment by compholio** [comment]
Would you mind attaching the specific IEEEtran.bst that you want to use?  I can probably update it without too much trouble.

**Comment by krishnakumarg1984** [comment]
@compholio  Yes, the `bst` file is just the official one from the `IEEEtran` package available from CTAN 
[http://mirrors.ctan.org/macros/latex/contrib/IEEEtran/bibtex/IEEEtran.bst](http://mirrors.ctan.org/macros/latex/contrib/IEEEtran/bibtex/IEEEtran.bst)

**Comment by compholio** [comment]
Give this version a try (jabbrv_IEEEtran.bst), that should hopefully do the trick :)
