### ISSUE TITLE
Check appropriate permissions without `sudo`

### ISSUE THREAD

**Issue by KiruyaMomochi** [compholio/jabbrv#23]
It's possible that some operating system doesn't have `sudo` installed. Then even the user is `root`, he may still get an error from the script:
```
ERROR: Super user permissions are required to continue, instead run:
sudo ./install.sh
```

Hence, we should check if user have appropriate permissions by other methods. For example, the `-w` operator of `test` command.

**Comment by compholio** [comment]
Conceivably you could replace "sudo" with $SUDO and set the value only if the test command fails.  Would you like to test and put together a patch for this?

**Comment by KiruyaMomochi** [comment]
#24.

**Comment by compholio** [comment]
Thanks for the fix, hopefully you're enjoying the package!
