### ISSUE TITLE
Support macOS for install script

### ISSUE THREAD

**Issue by alexreg** [compholio/jabbrv#25]
TeX Live installs to `/Library/TeX` on macOS and `texmf` is `~/Library/texmf`. Could you kindly support this?

**Comment by compholio** [comment]
It's been a while, but I thought MacTeX installed to /usr/local/texlive/<YEAR>/ - would you mind checking?  (I believe /Library/TeX is supposed to be a symlink)

**Comment by alexreg** [comment]
Ah, well in fact `/Library/TeX` is not a symlink, but `/Library/TeX/Root` is a symlink to `/Library/TeX/Distributions/.DefaultTeX/Contents/Root`, which is a symlink to `/usr/local/texlive/2020`!

**Comment by alexreg** [comment]
Also, `/Library/TeX/texbin` is a symlink to `/Library/TeX/Distributions/Programs/texbin` is symlink to `/Library/TeX/Distributions/.DefaultTeX/Contents/Programs/texbin` is a symlink to `/usr/local/texlive/2020/bin/x86_64-darwin`.

**Comment by compholio** [comment]
Could you please check that if you run the install script with the argument '/Library/TeX/Root' that it will install correctly?

**Comment by compholio** [comment]
Actually, it looks like there's a bug in the script and on MacTeX it was supposed to install to ${HOME}/Library/texmf, could you give that a try?

**Comment by alexreg** [comment]
@compholio That works, yep (if i specify the path manually).

**Comment by compholio** [comment]
I've just committed a fix for this ( dc9ae0f ), if you don't mind double checking that it works then I'd appreciate it.

**Comment by alexreg** [comment]
@compholio Thanks. It works in that `install.sh` exits without error, but the issue now is that it puts stuff in both `/usr/local/texlive` and `~/Library/texmf` -- which may or may not be correct (I'm not sure) -- but the files in the latter are owned by root, which is definitely a problem.

Also, would you be able to provide an uninstall script maybe? (It's certainly useful when testing this, for one.)

**Comment by compholio** [comment]
Would you please try manually deleting both instances and trying again?  I suspect that one of the two (/usr/local/texlive) is an old attempt.

**Comment by alexreg** [comment]
@compholio Ah, it seems the stuff in `/usr/local/texlive` is just part of a texhash (ls-R) database. Here's the output.

```sh
$ ./install.sh 
texhash: Updating /usr/local/texlive/2020/texmf-config/ls-R... 
texhash: Updating /usr/local/texlive/2020/texmf-dist/ls-R... 
texhash: Updating /usr/local/texlive/2020/texmf-var/ls-R... 
texhash: Updating /usr/local/texlive/texmf-local/ls-R... 
texhash: Done.
```

The problem with permissions seems to be that the script is incorrectly using sudo when unnecessary; the `[ -w ... ]` checks fails because the directories do not yet exist, not because they're in a location that's non-user-writable. I've created a PR that  believe solves this.
