### ISSUE TITLE
Not compatible with Biblatex 3.16

### ISSUE THREAD

**Issue by logological** [compholio/jabbrv#27]
jabbrv does not work with Biblatex 3.16, which is the latest stable release.  (I'm pretty sure it was working fine with Biblatex 3.15a, since that was the latest stable release back in September when I last used jabbrv.)  Here's what happens when you try to compile `biblatex-example.tex` from Git master:

```
$ pdflatex biblatex-example.tex 
This is pdfTeX, Version 3.14159265-2.6-1.40.21 (TeX Live 2020) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./biblatex-example.tex
LaTeX2e <2020-10-01> patch level 4
L3 programming layer <2021-02-18>
(/oldhome/psy/share/texlive/2020/texmf-dist/tex/latex/base/article.cls
Document Class: article 2020/04/10 v1.4m Standard LaTeX document class
(/oldhome/psy/share/texlive/2020/texmf-dist/tex/latex/base/size12.clo))
(/oldhome/psy/share/texlive/2020/texmf-dist/tex/latex/biblatex/biblatex.sty
(/oldhome/psy/share/texlive/2020/texmf-dist/tex/generic/pdftexcmds/pdftexcmds.s
ty
(/oldhome/psy/share/texlive/2020/texmf-dist/tex/generic/infwarerr/infwarerr.sty
) (/oldhome/psy/share/texlive/2020/texmf-dist/tex/generic/iftex/iftex.sty)
(/oldhome/psy/share/texlive/2020/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty))
(/oldhome/psy/share/texlive/2020/texmf-dist/tex/latex/etoolbox/etoolbox.sty)
(/oldhome/psy/share/texlive/2020/texmf-dist/tex/latex/graphics/keyval.sty)
(/oldhome/psy/share/texlive/2020/texmf-dist/tex/latex/kvoptions/kvoptions.sty
(/oldhome/psy/share/texlive/2020/texmf-dist/tex/generic/kvsetkeys/kvsetkeys.sty
)) (/oldhome/psy/share/texlive/2020/texmf-dist/tex/latex/logreq/logreq.sty
(/oldhome/psy/share/texlive/2020/texmf-dist/tex/latex/logreq/logreq.def))
(/oldhome/psy/share/texlive/2020/texmf-dist/tex/latex/base/ifthen.sty)
(/oldhome/psy/share/texlive/2020/texmf-dist/tex/latex/url/url.sty)
(/oldhome/psy/share/texlive/2020/texmf-dist/tex/latex/biblatex/blx-dm.def)
(/oldhome/psy/share/texlive/2020/texmf-dist/tex/latex/biblatex/blx-compat.def)
(/oldhome/psy/share/texlive/2020/texmf-dist/tex/latex/biblatex/biblatex.def)
(/oldhome/psy/share/texlive/2020/texmf-dist/tex/latex/biblatex/bbx/numeric-comp
.bbx
(/oldhome/psy/share/texlive/2020/texmf-dist/tex/latex/biblatex/bbx/numeric.bbx
(/oldhome/psy/share/texlive/2020/texmf-dist/tex/latex/biblatex/bbx/standard.bbx
)))
(/oldhome/psy/share/texlive/2020/texmf-dist/tex/latex/biblatex/cbx/numeric-comp
.cbx)
(/oldhome/psy/share/texlive/2020/texmf-dist/tex/latex/biblatex/biblatex.cfg))
(./jabbrv.sty (./jabbrv-ltwa-all.ldf) (./jabbrv-ltwa-en.ldf))
! Extra \endgroup.
\document ->\endgroup 
                      \@ifpackageloaded {biblatex}{ \DeclareFieldInputHandle...
l.17 \begin{document}
                     
? 
```

**Comment by compholio** [comment]
That's this code block:
https://github.com/compholio/jabbrv/blob/master/jabbrv.sty#L529

Would you mind seeing what happens when you cut out most of the functionality? (maybe something like this?:)
```
\global\let\jabbrv@begin@document=\document
\gdef\document{%
	\endgroup%
	\begingroup%
	\jabbrv@begin@document%
}
```

**Comment by logological** [comment]
I assume you want me to insert that code snippet (wrapped in `\makeatletter` and `\makeatother`) somewhere but I'm not clear as to where.  Are you talking about putting this in `biblatex-example.tex`?  If so, on what line exactly?

**Comment by moewew** [comment]
The problem can be reproduced without `biblatex` in
```latex
\documentclass{article}
\usepackage{jabbrv}
\begin{document}
Lorem
\end{document}
```
and is indeed related to
https://github.com/compholio/jabbrv/blob/faae76d040dcdbb2240d0b7cec552a43a19f3480/jabbrv.sty#L528-L539
as those lines interfere with LaTeX's new hook mechanism.


You probably want to use more standard interfaces like `etoolbox`' `\AtEndPreamble` (which uses the new hook mechanism with new LaTeX kernel versions and defines its own hooks for older LaTeX kernels) for this
```latex
\RequirePackage{etoolbox}
\AtEndPreamble{%
  \@ifpackageloaded{biblatex}
    {\DeclareFieldInputHandler{journaltitle}{%
     \def\NewValue{\JournalTitle{#1}}}}
    {}%
}
```

**Comment by logological** [comment]
Thanks for the information!  Apologies for having assumed this was a problem specific to Biblatex compatibility; it didn't occur to me that it might have been an update to LaTeX itself that was triggering the issue.

**Comment by moewew** [comment]
`etoolbox` is a perfectly fine package that is used by many other packages and people directly in their preamble, so I wouldn't directly rule it out just because it is not in the 'base' collection. (I doubt most people have only 'base' installed.) `etoolbox` is maintained by a member of the LaTeX team and I am pretty sure that it will continue to work and receive required updates in the future: Many people rely on it and so allowing it to break is not an option.

The advantage of using `etoolbox` here is obvious: You do not need to worry about the new hook mechanism. You most likely wouldn't even have noticed anything was up with the new LaTeX version. But if you roll your own version patching or heavily redefining core LaTeX commands such as `\document`, it is up to you to make sure everything works as expected and you don't break core functionality.

---

If you absolutely do not want to use `etoolbox`, you can have a look at its implementation of `\AtEndPreamble`

https://github.com/josephwright/etoolbox/blob/3552e3d9b96d5b95e25d08f1772f47b7b72cd604/etoolbox.sty#L1739-L1761

essentially, `etoolbox` branches on whether or not you are using a new or old LaTeX kernel

```latex
\providecommand\IfFormatAtLeastTF{\@ifl@t@r\fmtversion}
\IfFormatAtLeastTF{2020-10-01}
  {<New>}
  {<Old>}
```

With the new format `\AtEndPreamble` is just `\AddToHook{begindocument/before}`
```
\newrobustcmd*{\AtEndPreamble}{\AddToHook{begindocument/before}}%
```

With the old format, `\document` needs to be patched in the way `jabbrv.sty` does currently (not sure if the `\global`/`\gdef` are needed, I'd have thought `\def` would have been enough, but that's a hardly relevant).

**Comment by compholio** [comment]
> `etoolbox` is a perfectly fine package that is used by many other packages and people directly in their preamble, so I wouldn't directly rule it out just because it is not in the 'base' collection. (I doubt most people have only 'base' installed.) `etoolbox` is maintained by a member of the LaTeX team and I am pretty sure that it will continue to work and receive required updates in the future: Many people rely on it and so allowing it to break is not an option.
> ...

In many other packages that I've made I would be perfectly happy to use `etoolbox`, the issue I have here is that the "selling point" of this package is that it doesn't require a bunch of extra tools to do the job (there are many other ways to do journal title abbreviations, but they all require special tools).  However, I wouldn't mind using `etoolbox` if it's available and falling back to the custom code if it isn't.

How does this work for folks?:
```
% If working with biblatex then apply the journal title as a "field handler"
\@ifl@t@r\fmtversion{2020-10-01}{%
    \AddToHook{begindocument/before}{%
        \@ifpackageloaded{biblatex}{%
	        \DeclareFieldInputHandler{journaltitle}{%
		        \def\NewValue{\JournalTitle{##1}}%
	        }%
        }{}%
    }%
}{%
    \global\let\jabbrv@begin@document=\document%
    \gdef\document{%
        \endgroup%
        \@ifpackageloaded{biblatex}{%
	        \DeclareFieldInputHandler{journaltitle}{%
		        \def\NewValue{\JournalTitle{##1}}%
	        }%
        }{}%
        \begingroup%
        \jabbrv@begin@document%
    }%
}
```

**Comment by moewew** [comment]
Mhh, I guess I just wouldn't classify `etoolbox` as falling under 'a bunch of extra tools'. I would expect that most people who use LaTeX will have `etoolbox` installed (for example `etoolbox` is required by `biblatex`, so your `biblatex` users will have `etoolbox`). But *de gustibus ...*

There is a small typo in the branch of code for the new kernel. `\AddToHook{begindocument/before}` does not start a macro definition, so you just want `#1` and not `##1`
```latex
% If working with biblatex then apply the journal title as a "field handler"
\@ifl@t@r\fmtversion{2020-10-01}{%
    \AddToHook{begindocument/before}{%
        \@ifpackageloaded{biblatex}{%
          \DeclareFieldInputHandler{journaltitle}{%
            \def\NewValue{\JournalTitle{#1}}%
          }%
        }{}%
    }%
}{%
    \global\let\jabbrv@begin@document=\document%
    \gdef\document{%
        \endgroup%
        \@ifpackageloaded{biblatex}{%
          \DeclareFieldInputHandler{journaltitle}{%
           \def\NewValue{\JournalTitle{##1}}%
          }%
        }{}%
        \begingroup%
        \jabbrv@begin@document%
    }%
}
```
(I have only tested with the new version of the kernel.)

**Comment by compholio** [comment]
Thanks, I'm able to test on the old kernel - so I think we've got it covered now.

It's too bad I don't know if biblatex is loaded until the preamble is done or I'd just check for biblatex first ;)
