### ISSUE TITLE
Compatibility with overleaf

### ISSUE THREAD

**Issue by jsbryaniv** [compholio/jabbrv#29]
Is there a way to integrate jabbrv into overleaf? If so, then there should be a description of how to do this in the code documentation. If not, then I think there should be a statement to this affect in the FAQ.

**Comment by compholio** [comment]
I have never used overleaf, but from a quick search it sounds like you can include the jabbrv files in the folder with your .tex file and it will allow you to use the jabbrv package ( see https://tex.stackexchange.com/questions/414780/how-to-add-a-package-in-overleaf?noredirect=1&lq=1 ).

**Comment by compholio** [comment]
You will definitely need `jabbrv.sty` + `jabbrv-ltwa-all.ldf` + the dictionary for the language you use (probably `jabbrv-ltwa-en.ldf`) + the biblatex style sheet you want (one of the `.bst` files).  If you want to just do a quick test then you may wish to use `latex-example.tex` as a starting point (and include `jabbrv_unsrt.bst` and `example.bib` to go along with it).

**Comment by jsbryaniv** [comment]
This worked! Is it ok if I publish this as a template on Overleaf so that other people can see a minimally working example?

**Comment by compholio** [comment]
Absolutely, if you want to add instructions to the README.md and make a pull request I would happily include that as well.

**Comment by jsbryaniv** [comment]
Apologies, I am not very familiar with how to do push/pull requests (which is why I am using Overleaf!). I can, however, give a link to my minimal working overleaf example if this helps: https://www.overleaf.com/read/drzdrzrgrrrp

**Comment by jsbryaniv** [comment]
Is there an example for how to use jabbrv in a revtex document class? I tried uploading the same files into another project and the journal names remain unabbreviated

**Comment by jsbryaniv** [comment]
Yes that works thanks!

**Comment by jsbryaniv** [comment]
By the way, the template was published at a more permanent address here: https://www.overleaf.com/latex/templates/automatic-journal-abbreviations/mxfsdscmvxcr
I think this would be good to add to the FAQ or readme

**Comment by compholio** [comment]
Done, glad this was so easy to get going for you!
