### ISSUE TITLE
Duplicate Spaces

### ISSUE THREAD

**Issue by DorianRudolph** [compholio/jabbrv#30]
Abbreviations cause duplicate spaces. The first commit where this happens is 07a8d7f016df440671f126569c3ef0a2d7879602.

![image](https://user-images.githubusercontent.com/10325838/154992064-e003b83f-2d09-45b3-9991-d9eada6e337d.png)

The previous commit looks fine:

![image](https://user-images.githubusercontent.com/10325838/154992651-0abf9965-a682-4890-ab39-2a19c4663af5.png)

I am using texlive 2021.61403-1 on Arch Linux.

**Comment by compholio** [comment]
I believe that this should now be fixed, please give it a try and let me know.  (Sorry it's taken me a while to look at this, things have been a little crazy.)
