### ISSUE TITLE
Can't compile biblatex-example in jabbrv-master folder

### ISSUE THREAD

**Issue by shadyaristotelessnail** [compholio/jabbrv#36]
Hello everyone,

i downloaded the newest version of jabbrv and i'm unable to compile biblatex-example.tex 
inside the folder jabbrv-master
with visual studio code and the extension LaTeX Workshop.

Here is the source file:

`
\documentclass[letterpaper,12pt]{article}

% compressed (numeric) citations:
\usepackage[backend=biber, style=numeric-comp]{biblatex}

% Define custom commands used in the BibTeX file:
\newcommand{\tjri}{Test Journal of Reference Information}

\addbibresource{example.bib}

% Remove ``[warnundef]'' to get rid of undefined abbreviation warnings:
\usepackage[warnundef]{jabbrv}

% Defining a custom abbreviation:
\DefineJournalAbbreviation{Test}{Tes} % <-- Note that there is no period!

\begin{document}

Test \cite{ref:TestNoPeriod,ref:Test,ref:TestPeriod,ref:TestPeriodTwoWords,ref:TestPeriodRefInf,ref:TestPeriodInf,
ref:TestMyAbbrvOneWord,ref:TestMyAbbrvTwoWords,ref:TestPeriodInfPeriod,ref:CmdTest,ref:AbbrvTest,ref:SymbolTest}.
\JournalTitle{Briefings in Functional Genomics}.

\printbibliography

\end{document}
`

The output of the compiler is included in output.txt
[output.txt](https://github.com/compholio/jabbrv/files/10155588/output.txt)

**Comment by compholio** [comment]
I can't easily test biblatex support at the moment, can you roll back to commit `f00da3a6a3abffd26b49a89eaff05493ab96bb67` and see if that works for you?

**Comment by shadyaristotelessnail** [comment]
Works flawlessly, with this roll back it also work again for my other latex project that i'm using right now.
Many thanks!

I first loaded biblatex and then jabbrv like in the example.

**Comment by shadyaristotelessnail** [comment]
I'm not so proficent with git, i can give it a go next week.

**Comment by compholio** [comment]
No problem, it's pretty simple.  To start:
```
git bisect start
git bisect good f00da3a6a3abffd26b49a89eaff05493ab96bb67
git bisect bad origin
```
git will then split it into the middle and stop for you to test, if it works then run:
```
git bisect good
```
if it doesn't then run:
```
git bisect bad
```
repeat this process until it reports back the first broken commit

**Comment by shadyaristotelessnail** [comment]
I did the bisect.
It wasn't able to compile at repo [46786077c7f21e80e67079f8390b248574da89b2]

Here is the output

`PS C:\Users\Ibm\jabbrv> git bisect start
status: waiting for both good and bad commits
PS C:\Users\Ibm\jabbrv> git bisect good f00da3a6a3abffd26b49a89eaff05493ab96bb67
status: waiting for bad commit, 1 good commit known
PS C:\Users\Ibm\jabbrv> git bisect bad origin
Bisecting: 16 revisions left to test after this (roughly 4 steps)
[0e0dacb9399141f42645bda476c64601b4e014a0] treat non-breaking spaces in titles properly
PS C:\Users\Ibm\jabbrv> git bisect good
Bisecting: 8 revisions left to test after this (roughly 3 steps)
[7259152f0244aa7d6054098b9fef3eeec5ba2872] only output one space for unabbreviated words
PS C:\Users\Ibm\jabbrv> git bisect good
Bisecting: 4 revisions left to test after this (roughly 2 steps)
[2e29793d8319987e7f3c1059b022b6908989a32e] fix inappropriate indent level for journal word separator routine
PS C:\Users\Ibm\jabbrv> git bisect good
Bisecting: 2 revisions left to test after this (roughly 1 step)
[46786077c7f21e80e67079f8390b248574da89b2] fix \JournalTitle followed by nothing (new paragraph)
PS C:\Users\Ibm\jabbrv> git bisect bad
Bisecting: 0 revisions left to test after this (roughly 0 steps)
[d922ed6c3880538817d3ad3c39bc745f88702941] add a note to the README about BibLaTeX
PS C:\Users\Ibm\jabbrv> git bisect good
46786077c7f21e80e67079f8390b248574da89b2 is the first bad commit
commit 46786077c7f21e80e67079f8390b248574da89b2
Author: Erich E. Hoover <erich.e.hoover@gmail.com>
Date:   Tue Sep 20 15:11:04 2022 -0600

    fix \JournalTitle followed by nothing (new paragraph)

 jabbrv.sty | 22 ++++++++++++++--------
 1 file changed, 14 insertions(+), 8 deletions(-)
PS C:\Users\Ibm\jabbrv>`

Hope that helps!

**Comment by Ivo-PV00** [comment]
Hello,

I am having sort of the same problem, but I can't fix it with this commit. I am using pdfLaTex to compile a report document, and it gives an error for all of my references:

Package natbib Warning: Citation `citation' on page X undefined on input line Y.

I am using natbib with jabbrv_abbrv and the english language file. The preamble file is:

\usepackage{graphicx}
\graphicspath{{Images/}}
\usepackage{wrapfig}
\usepackage{url}

%margins
\usepackage{geometry}
\geometry{verbose,margin=2.5cm}

%referrence phantom sections
\usepackage{hyperref}

%color in text
\usepackage{xcolor}

\usepackage{indentfirst}

%bibliography with citation order; include in TOC
\usepackage[numbers,sort&compress]{natbib}
\usepackage{jabbrv}

%AMS mathematical expressions
\usepackage{amsmath}
\usepackage{amsfonts}
\usepackage{amsthm}

\newcommand{\eqnref}[1]{Eq.(\ref{#1})}
\newcommand{\figref}[1]{Fig.(\ref{#1})}

%make nomenclature
\usepackage{nomencl}
\makenomenclature

%hyphenate automatically
\usepackage{soul}

%set font type to Arial
\renewcommand{\rmdefault}{phv}
\renewcommand{\sfdefault}{phv}

%set title and subtitle font type and size

\def\nT{% 16 pt normal
  \usefont{T1}{phv}{m}{n}\fontsize{16pt}{16pt}\selectfont}
\def\bT{% 16 pt bold
  \usefont{T1}{phv}{b}{n}\fontsize{16pt}{16pt}\selectfont}
\def\nST{% 14 pt normal
  \usefont{T1}{phv}{m}{n}\fontsize{14pt}{14pt}\selectfont}
\def\bST{% 14 pt bold
  \usefont{T1}{phv}{b}{n}\fontsize{14pt}{14pt}\selectfont}
\def\nSST{% 12 pt normal
  \usefont{T1}{phv}{m}{n}\fontsize{12pt}{12pt}\selectfont}
\def\bSST{% 12 pt bold
  \usefont{T1}{phv}{b}{n}\fontsize{12pt}{12pt}\selectfont}

%extension of commands for tables
\usepackage{booktabs}

%define degrees
\newcommand{\degree}{\ensuremath{^\circ\,}}

%set language and characters
\usepackage[utf8]{inputenc}

%line spacing
\usepackage{setspace}
\onehalfspacing

%set predefined statements and commands
\def\sp{\vspace{1cm}}
\def\ThesisTo{\nSST{Thesis to obtain the Master of Science Degree in} \\ \vspace{1cm}}
\def\ThesisSup{\nSST{Supervisor:}}
\def\ThesisSups{\nSST{Supervisors:}}
\def\Juri{\bST{Examination Committee} \\ \vspace{1cm}}
\def\ChairP{\nSST{Chairperson:}}
\def\MoC{\nSST{Member of the Committee:}}
\def\Decl{\vfill
    \textit{Declaration} \\
    \textit{I declare that this document is an original work of my own authorship and that it fulfills all
    the requirements of the Code of Conduct and Good Practices of the Universidade de
    Lisboa.}
    \vfill}


I am calling the bibliography in the main, like this:

(...)
\clearpage
\phantomsection
\addcontentsline{toc}{section}{\bibname}
\bibliographystyle{jabbrv_abbrv}
\bibliography{Bib}
(...)

I am not very advanced on LaTex, although I've been using it for a while, so I tried to fix the error and the only thing that worked was changing the compiler to XeLaTex, but in that case I have more problems with the rest of the document. So I admit I might be doing some mistake in the coding, but I can't tell where.

Thank you in advance!

**Comment by antifermion** [comment]
I also have the issue and agree with @shadyaristotelessnail that d922ed6c is the last working commit
