### ISSUE TITLE
How to reduce long author lists to "First author et al."? by changing the `jabbrv_unsrt.bst` file?

### ISSUE THREAD

**Issue by Tinaatucsd** [compholio/jabbrv#38]
I am trying to change the `.bst` file to achieve the same goal posted here. 

[https://tex.stackexchange.com/questions/26575/bibtex-how-to-reduce-long-author-lists-to-firstauthor-et-al/26582#26582](url)

But I could not quite figure out how. 

Please shine a light on me. 

Thank you very much!

Best,
Hui

**Comment by compholio** [comment]
Try [this file](https://gist.githubusercontent.com/compholio/7e39a3b661ad111e0d958afc1a76c453/raw/1e46931800d57ddb6284a10ec2b98dd8de345583/jabbrv_unsrt.bst).

**Comment by Tinaatucsd** [comment]
Thank you very much for your prompt solution!

After adjusting the `numnames #5` and `nameptr #1`, I am able to achieve the requirement of 

> References should list up to 5 authors. If a reference has more than 5 authors, include the first author followed by et al.

I really appreciated your work and contribution!

Hope you have a fulfilling day!
