### ISSUE TITLE
Conflicts with amsmath, orcidlink

### ISSUE THREAD

**Issue by dave-willis** [compholio/jabbrv#39]
Using the latest version of jabbrv with amsmath and/or orcidlink breaks certain commands/fails to compile all together. 

A minimal example for amsmath. This document compiles fine:

```
\documentclass{article} 

\usepackage{amsmath}
\usepackage{jabbrv}

\begin{document}

test

\begin{equation}
T = a
\end{equation}

\end{document}
```

But when I include \left( \right) commands: 

```
\documentclass{article} 

\usepackage{amsmath}
\usepackage{jabbrv}

\begin{document}

test

\begin{equation}
\left(T\right) = a
\end{equation}

\end{document}
```

I get the error:

`./test.tex:15: Undefined control sequence. l.15 \left(T\right) = a`

If I comment out the jabbrv import then the document compiles fine and I get the expected result. 

With orcidlink there is a direct conflict in just importing the two packages. The document

```
\documentclass{article} 

\usepackage{jabbrv}
\usepackage{orcidlink}

\begin{document}

test

\end{document}
```

Compiles fine if any one, or both, of the packages are commented out, but when they are both active then I get the error:

```
4: Undefined control sequence.
\pgfrcs@final ...date \space v\pgfversion \space( 
                                                  \pgfrevision) ]}\expandaft...
l.144 \ProvidesPackageRCS{pgfrcs.code.tex}
```

There may be more conflicts - I recently fully updated my latex install for other reasons and the large document I'm currently working on broke, these were the two issues I was able to isolate with the newest version of jabbrv.

Both of these issues, and any other issues that may exist in my document, are fixed by reverting to an older version of jabbrv.sty and *.ldf files, pre-2018 as far as I can tell. I've not been able to identify specific changes that have caused the error, but any fix would be appreciated!

**Comment by Francis-Hsu** [comment]
The problem is in line 252 of `jabbrv.sty`:
```
\catcode`\(11\relax
\catcode`\)11\relax
\global\let\jabbrv@slash@orig=\slash
\global\let\jabbrv@space@orig=\ 
\global\let\jabbrv@underscore@orig=\_
\global\let\jabbrv@openparen@orig=(
\global\let\jabbrv@closeparen@orig=)
```
This part set the [catcode](https://en.wikibooks.org/wiki/TeX/catcode) of `(` and `)` to 11 but never change it back, so any time a pair of parentheses is used things would go haywire.  Adding:
```
\catcode`\(12\relax
\catcode`\)12\relax
```
to the end of the file should fix it.

**Comment by compholio** [comment]
Thanks for spotting that, looks like I returned it to the wrong catcode (it was earlier set to \active/13) and I incorrectly set it to 11/letter.
