### ISSUE TITLE
Some special characters not working in journal titles

### ISSUE THREAD

**Issue by mjthoraval** [compholio/jabbrv#5]
After using jabbrv, it is not possible anymore to use the following special characters in the journal titles:
'~' '\ ' '\_' and diacritics followed by a space such as '\^ '
These characters are working fine without jabbrv.

For example, the format of JFM includes the following format in the bibtex file:
  journal = 	 {J.~Fluid Mech.},
https://www.cambridge.org/core/journals/journal-of-fluid-mechanics/information/instructions-contributors

**Comment by compholio** [comment]
The work I did for #28 gave me an idea on how to solve this for this case as well.  I'd need a good example for diacritics followed by a space, but I can now cover '~', '\ ', '\_', and '\slash'.  I know it's been a while, but if you open another bug for the diacritics issue with an example then I'll see if the same thing can work for that case.
