### ISSUE TITLE
Compatibility with BibLaTeX

### ISSUE THREAD

**Issue by ElieGouzien** [compholio/jabbrv#9]
Hi, recently I have been stuck in trying to use `jabbrv` with `BibLaTeX`.
BibLaTeX developers (more exactly moewew) showed me how to combine them.

Technical details are here:
https://github.com/plk/biblatex/issues/795#issuecomment-496370805

I really think it worth adding it into the doc.
I can propose a pull request, but where to add it? Is the begining of jabbrv.sty the good place for it?

**Comment by compholio** [comment]
Well, it depends on whether any of these should/are order dependent:
```
\usepackage{biblatex}
\usepackage{jabbrv}
\DeclareFieldInputHandler...
\addbibresource{biblatex-examples.bib}
```
Generally speaking, you want to use \AddBeginDocument and have the command dependent upon whether biblatex is loaded.  This technique ensures that jabbrv can be loaded either before or after biblatex.  However, that approach requires that \addbibresource not require \DeclareFieldInputHandler to occur first.  Does that make sense?

**Comment by ElieGouzien** [comment]
Nice work! And lot of thanks!

However, have you noticed that for now `jabbrv` needs to be loaded before `biblatex`?

**Comment by compholio** [comment]
I'm not seeing that, the example I added actually has jabbrv loaded after biblatex... Would you mind putting together a minimal example and opening a new bug?

**Comment by ElieGouzien** [comment]
I've opened a new issue. In the example jabbrv is actually loaded twice, one time before and one time after biblatex.
